<?php

/**
 * @file
 * Provide a sitemap for the list of available enabled modules.
 */

use \Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function module_sitemap_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    case 'help.page.module_sitemap':
      return t('To access the module sitemap, click @here_link. This module gives you the ability to look at all of the paths for each module holistically.', array('@here_link' => '<a href="/module-sitemap">here</a>'));
  }
}
